### ISSUE TITLE
imap_tools

### ISSUE THREAD

**Issue by mmeinesz** [caltabid/imap-delete-attachments#2]
hi and thanks for your script.
I have a suggesion: You can check before if all needed python modules are available.
also I have a question as I don't know anything about python:
What is happening here?:

```
# pip install imap_tools
Collecting imap_tools
  Using cached https://files.pythonhosted.org/packages/7c/91/287526663b51f06812bd20ecb142dc636e43b2394f6cd5c6167d57a12972/imap-tools-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-CSmcRN/imap-tools/setup.py", line 6
        def get_version(package: str) -> str:
                               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CSmcRN/imap-tools/

```

**Comment by caltabid** [comment]
Dear mmeinesz,
I'm closing the issue since it is not related to my project code.
I suggest you to look for this issue on Internet, in particular the installation instruction of [imap_tools](https://github.com/ikvk/imap_tools), I think you misspelled the package name.
